tweet = {u'contributors': None, u'truncated': False,
         u'text': u'One of my heroines #Simone Veil-has died.An MEP with me in 1979,survivor of Auschwitz,former French Minister of Health,inspirational woman.',
         u'is_quote_status': False, u'in_reply_to_status_id': None, u'id': 881258763327557634, u'favorite_count': 0,
         u'source': u'<a href="http://twitter.com/#!/download/ipad" rel="nofollow">Twitter for iPad</a>',
         u'retweeted': False, u'coordinates': None, u'timestamp_ms': u'1498943436830',
         u'entities': {u'user_mentions': [], u'symbols': [], u'hashtags': [{u'indices': [19, 26], u'text': u'Simone'}],
                       u'urls': []}, u'in_reply_to_screen_name': None, u'id_str': u'881258763327557634',
         u'retweet_count': 0, u'in_reply_to_user_id': None, u'favorited': False,
         u'user': {u'follow_request_sent': None, u'profile_use_background_image': True, u'default_profile_image': False,
                   u'id': 460338359, u'verified': True,
                   u'profile_image_url_https': u'https://pbs.twimg.com/profile_images/859790012417806337/A2oJWW9m_normal.jpg',
                   u'profile_sidebar_fill_color': u'DDEEF6', u'profile_text_color': u'333333', u'followers_count': 6476,
                   u'profile_sidebar_border_color': u'C0DEED', u'id_str': u'460338359',
                   u'profile_background_color': u'C0DEED', u'listed_count': 266,
                   u'profile_background_image_url_https': u'https://abs.twimg.com/images/themes/theme1/bg.png',
                   u'utc_offset': None, u'statuses_count': 1168,
                   u'description': u'The Labour MP for the Cynon Valley constituency', u'friends_count': 829,
                   u'location': None, u'profile_link_color': u'1DA1F2',
                   u'profile_image_url': u'http://pbs.twimg.com/profile_images/859790012417806337/A2oJWW9m_normal.jpg',
                   u'following': None, u'geo_enabled': True,
                   u'profile_banner_url': u'https://pbs.twimg.com/profile_banners/460338359/1498228926',
                   u'profile_background_image_url': u'http://abs.twimg.com/images/themes/theme1/bg.png',
                   u'name': u'Ann Clwyd', u'lang': u'en', u'profile_background_tile': False, u'favourites_count': 405,
                   u'screen_name': u'AnnClwyd', u'notifications': None, u'url': None,
                   u'created_at': u'Tue Jan 10 17:08:10 +0000 2012', u'contributors_enabled': False, u'time_zone': None,
                   u'protected': False, u'default_profile': True, u'is_translator': False}, u'geo': None,
         u'in_reply_to_user_id_str': None, u'lang': u'en', u'created_at': u'Sat Jul 01 21:10:36 +0000 2017',
         u'filter_level': u'low', u'in_reply_to_status_id_str': None, u'place': {u'full_name': u'Cardiff, Wales',
                                                                                 u'url': u'https://api.twitter.com/1.1/geo/id/68f3012fe4848e35.json',
                                                                                 u'country': u'United Kingdom',
                                                                                 u'place_type': u'city',
                                                                                 u'bounding_box': {u'type': u'Polygon',
                                                                                                   u'coordinates': [[[
                                                                                                                         -3.278624,
                                                                                                                         51.447362],
                                                                                                                     [
                                                                                                                         -3.278624,
                                                                                                                         51.546641],
                                                                                                                     [
                                                                                                                         -3.080976,
                                                                                                                         51.546641],
                                                                                                                     [
                                                                                                                         -3.080976,
                                                                                                                         51.447362]]]},
                                                                                 u'country_code': u'GB',
                                                                                 u'attributes': {},
                                                                                 u'id': u'68f3012fe4848e35',
                                                                                 u'name': u'Cardiff'}}
